version: "3.8"
services:
  api:
    platform: linux/amd64
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: api-test
    volumes:
      - ./app:/app
    ports:
      - "8081:8081"

  postgresql:
    image: postgres:14.1-alpine
    container_name: postgres-test
    command: postgres -c max_connections=200
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./util-containers/postgresql/data:/var/lib/postgresql/data
      - ./util-containers/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
  
  prometheus:
    image: prom/prometheus:v2.45.2
    #image: prom/prometheus-linux-arm64:v2.40.2
    user: root
    volumes:
      - './etc/prometheus/:/etc/prometheus/'
      - './var/prometheus/prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - '3000:3000'
    volumes:
      - './var/grafana/grafana_data:/var/lib/grafana'
      - './etc/grafana/provisioning/:/etc/grafana/provisioning/'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000

  pushgateway:
    image: prom/pushgateway
    ports:
      - '9091:9091'
    depends_on:
      - prometheus

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    user: root
    ports:
      - '9187:9187'
    environment:
      - 'collect.info_schema.tablestats=true'
      - 'collect.info_schema.userstats=true'
      - 'collect.info_schema.query_response_time=true'
      - 'collect.auto_increment.columns=true'
      - 'collect.perf_schema.tableiowaits=true'
      - 'collect.perf_schema.tablelocks=true'
      - DATA_SOURCE_NAME=postgresql://postgres:password@postgresql:5432/postgres?sslmode=disable
    depends_on:
      - postgresql
